trigger:
- main

pool:
  vmImage: ubuntu-latest


jobs:
- job: build_docker_image
  steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    
    - bash: echo Contents in System Default Working Directory; ls $(System.DefaultWorkingDirectory)        
    - bash: echo Before copying Contents in Build Artifact Directory; ls $(Build.ArtifactStagingDirectory)
    
    #- task: Docker@2
    #  inputs:
    #    containerRegistry: 'azure-acr-service-connection'
    #    repository: 'poojastores'
    #    command: 'buildAndPush'
    #    Dockerfile: '**/Dockerfile'
    #    tags: 'latest'
    #    addPipelineData: false
    #    addBaseImageData: false
    - task: CopyPublishBuildArtifacts@1
      inputs:
        CopyRoot: '$(System.DefaultWorkingDirectory)'
        Contents: 'Dockerfile'
        ArtifactName: 'Dockerfile'
        ArtifactType: 'FilePath'
    - bash: echo Contents in System Default Working Directory; ls $(System.DefaultWorkingDirectory)        
    - bash: echo Before copying Contents in Build Artifact Directory; ls $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'image'
        publishLocation: 'Container'