trigger:
- main

pool:
  vmImage: ubuntu-latest


jobs:
- job: build_docker_image
  steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'azure-acr-service-connection'
        repository: 'poojastores'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
